# Generated by Django 5.2.9 on 2025-12-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtokenlog',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authtokenlog',
            name='refresh_token',
            field=models.TextField(unique=True),
        ),
    ]
