# Generated by Django 5.2.9 on 2026-01-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auditlogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditlogmodel',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='auditlogmodel',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditlogmodel',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditlogmodel',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
