# Generated by Django 5.2.9 on 2026-01-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_auditlogmodel_city_alter_auditlogmodel_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='professional_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
