# Generated by Django 5.2.9 on 2026-01-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_usermodel_professional_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='professional_id',
            field=models.CharField(max_length=255),
        ),
    ]
