# Generated by Django 5.2.9 on 2026-01-17 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0001_initial'),
        ('Receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionistmodel',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionists', to='Branch.branchmodel'),
        ),
    ]
